(() => {
"use strict";
const $=id=>document.getElementById(id),C=$("game"),X=C.getContext("2d"),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),unit=(x,y)=>{const n=Math.hypot(x,y)||1;return{x:x/n,y:y/n}};
const ui={intro:$("intro"),result:$("result"),eyebrow:$("resultEyebrow"),title:$("resultTitle"),body:$("resultBody"),skill1:$("skill1Label"),skill2:$("skill2Label"),stick:$("stick"),knob:$("stickKnob")};
const input={just:new Set(),held:Object.create(null),keys:new Set(),move:{x:0,y:0},clearFrame(){this.just.clear()},pressed(a){return this.just.has(a)}};
const styles=[{name:"听刃",skills:["震刃","回锋"]},{name:"流影",skills:["掠影","追风斩"]}];
const enemyMoves={
 cut:{name:"明斩",hint:"可挡 · 可弹 · 可拼",windup:.52,active:.13,recovery:.54,damage:18,posture:24,range:96,level:1},
 delay:{name:"迟锋",hint:"延迟二拍 · 不要早按",windup:.9,active:.14,recovery:.68,damage:25,posture:34,range:103,level:2},
 quick:{name:"回身斩",hint:"短前摇 · 抢回合",windup:.38,active:.12,recovery:.48,damage:16,posture:20,range:91,level:1},
 red:{name:"裂地",hint:"危 · 不可挡，只能闪",windup:.84,active:.18,recovery:.92,damage:38,posture:42,range:122,level:3,unblockable:true}
};
const chain=[
 {name:"长刀一式",windup:.11,active:.11,recovery:.17,damage:12,posture:14,range:100,level:1},
 {name:"长刀二式",windup:.13,active:.11,recovery:.18,damage:14,posture:17,range:104,level:1},
 {name:"长刀三式",windup:.21,active:.11,recovery:.3,damage:21,posture:27,range:111,level:2}
];
class Fighter{
 constructor(kind){this.kind=kind;this.maxHealth=kind==="player"?120:155;this.maxPosture=kind==="player"?100:120;this.reset()}
 reset(){this.pos=this.kind==="player"?{x:430,y:415}:{x:805,y:315};this.health=this.maxHealth;this.posture=this.maxPosture;this.state="idle";this.attack=null;this.timer=0;this.hit=false;this.face=this.kind==="player"?-.5:2.6;this.stagger=0;this.invuln=0;this.perfect=0;this.guardAt=-99;this.edge=this.kind==="player"?1:0;this.style=0;this.combo=0;this.attackCooldown=this.kind==="enemy"?.85:0;this.pattern=["cut","delay","quick","red"];this.patternIndex=0;this.flash=0}
 faceToward(p){this.face=Math.atan2(p.y-this.pos.y,p.x-this.pos.x)}
 forward(){return{x:Math.cos(this.face),y:Math.sin(this.face)}}
 alive(){return this.health>0}
}
class Game{
 constructor(){this.player=new Fighter("player");this.enemy=new Fighter("enemy");this.logs=[];this.particles=[];this.running=false;this.resultShown=false;this.time=0;this.hitStop=0;this.shake=0;this.initiative=0;this.telegraph=null;this.reset(false)}
 reset(start=false){this.player.reset();this.enemy.reset();this.running=start;this.resultShown=false;this.time=0;this.hitStop=0;this.shake=0;this.initiative=0;this.telegraph=null;this.logs=[{text:"校刀院封门。读招、接刀、夺势、破势。",ttl:4}];this.particles=[];ui.result.classList.add("hidden");if(start)ui.intro.classList.add("hidden");this.syncStyle()}
 syncStyle(){ui.skill1.textContent=styles[this.player.style].skills[0];ui.skill2.textContent=styles[this.player.style].skills[1]}
 log(text){this.logs.unshift({text,ttl:2.1});this.logs.length=Math.min(4,this.logs.length)}
 update(dt){dt=Math.min(.05,dt);this.time+=dt;this.logs.forEach(l=>l.ttl-=dt);this.logs=this.logs.filter(l=>l.ttl>0);this.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.ttl-=dt});this.particles=this.particles.filter(p=>p.ttl>0);this.shake=Math.max(0,this.shake-dt*30);if(input.pressed("restart"))this.reset(true);if(!this.running||this.resultShown)return;if(this.hitStop>0){this.hitStop-=dt;return}this.updatePlayer(dt);this.updateEnemy(dt);this.tick(this.player,dt);this.tick(this.enemy,dt);for(const f of [this.player,this.enemy]){f.pos.x=clamp(f.pos.x,190,1090);f.pos.y=clamp(f.pos.y,180,615)}this.finish()}
 updatePlayer(dt){const p=this.player;if(!p.alive()||p.stagger>0)return;if(input.pressed("switch")&&p.state==="idle"){p.style=1-p.style;this.syncStyle();this.log(`换式：${styles[p.style].name}`)}if(input.pressed("dodge")&&["idle","guard"].includes(p.state))this.dodge();if(input.pressed("skill1"))this.skill(0);if(input.pressed("skill2"))this.skill(1);if(input.pressed("attack"))this.playerAttack();if(input.held.guard&&p.state==="idle"){p.state="guard";p.guardAt=this.time}if(!input.held.guard&&p.state==="guard")p.state="idle";if(["idle","guard"].includes(p.state)){const k={x:(input.keys.has("KeyD")||input.keys.has("ArrowRight")?1:0)-(input.keys.has("KeyA")||input.keys.has("ArrowLeft")?1:0),y:(input.keys.has("KeyS")||input.keys.has("ArrowDown")?1:0)-(input.keys.has("KeyW")||input.keys.has("ArrowUp")?1:0)},m=Math.hypot(input.move.x,input.move.y)>Math.hypot(k.x,k.y)?input.move:k,n=unit(m.x,m.y),speed=255*(p.state==="guard"?.48:1)*clamp(Math.hypot(m.x,m.y),0,1);p.pos.x+=n.x*speed*dt;p.pos.y+=n.y*speed*dt;if(distance(p.pos,this.enemy.pos)<430)p.faceToward(this.enemy.pos)}}
 updateEnemy(dt){const e=this.enemy;if(!e.alive()||e.stagger>0||e.state!=="idle")return;e.faceToward(this.player.pos);const d=distance(e.pos,this.player.pos);if(d>88){const n=unit(this.player.pos.x-e.pos.x,this.player.pos.y-e.pos.y);e.pos.x+=n.x*155*dt;e.pos.y+=n.y*155*dt}e.attackCooldown-=dt;if(d<116&&e.attackCooldown<=0)e.chooseAttack()}
 tick(f,dt){f.flash=Math.max(0,f.flash-dt);f.invuln=Math.max(0,f.invuln-dt);f.perfect=Math.max(0,f.perfect-dt);if(f.stagger>0){f.stagger-=dt;if(f.stagger<=0&&f.alive()){if(f.posture<=0)f.posture=f.maxPosture*.45;f.state="idle";f.attack=null;if(f.kind==="enemy")f.attackCooldown=.65}return}if(!f.attack){if(f.state==="idle")f.posture=Math.min(f.maxPosture,f.posture+8*dt);return}f.timer+=dt;const a=f.attack;if(f.timer>=a.windup&&f.timer<a.windup+a.active){f.state="active";if(!f.hit){f.hit=true;this.resolve(f,f===this.player?this.enemy:this.player,a)}}else if(f.timer>=a.windup+a.active+a.recovery){f.attack=null;f.hit=false;f.timer=0;f.state="idle";if(f.kind==="enemy")f.attackCooldown=.3}else if(f.timer>=a.windup+a.active)f.state="recover"}
 start(f,a){f.attack={...a};f.timer=0;f.hit=false;f.state="windup";f.faceToward(f===this.player?this.enemy.pos:this.player.pos);if(a.lunge){const n=f.forward();f.pos.x+=n.x*a.lunge;f.pos.y+=n.y*a.lunge}if(a.through){const n=unit(this.enemy.pos.x-f.pos.x,this.enemy.pos.y-f.pos.y);f.pos={x:this.enemy.pos.x+n.x*48,y:this.enemy.pos.y+n.y*48}}if(a.chase){const n=unit(this.enemy.pos.x-f.pos.x,this.enemy.pos.y-f.pos.y);f.pos={x:this.enemy.pos.x-n.x*54,y:this.enemy.pos.y-n.y*54}}if(f.kind==="enemy")this.telegraph=a}
 playerAttack(){const p=this.player;if(!["idle","guard","recover"].includes(p.state))return;if(this.enemy.posture<=0&&distance(p.pos,this.enemy.pos)<110){this.start(p,{name:"处决",windup:.18,active:.1,recovery:.42,damage:58,posture:0,range:120,level:3,execute:true});return}this.start(p,{...chain[p.combo]});p.combo=(p.combo+1)%chain.length}
 skill(slot){const p=this.player;if(!["idle","guard"].includes(p.state))return;if(p.edge<2){this.log("锋意不足：先用本流派的正确操作夺回节奏。");return}p.edge-=2;const moves=p.style===0?[{name:"震刃",windup:.16,active:.14,recovery:.28,damage:7,posture:38,range:132,level:2,radial:true},{name:"回锋",windup:.1,active:.12,recovery:.34,damage:25,posture:28,range:125,level:3,lunge:55}]:[{name:"掠影",windup:.08,active:.1,recovery:.2,damage:14,posture:14,range:120,level:1,through:true},{name:"追风斩",windup:.12,active:.11,recovery:.26,damage:23,posture:22,range:132,level:2,chase:true}];this.start(p,moves[slot]);this.log(`${moves[slot].name}：消耗二格锋意。`)}
 dodge(){const p=this.player,m=Math.hypot(input.move.x,input.move.y)>.05?input.move:p.forward(),n=unit(m.x,m.y);p.pos.x+=n.x*62;p.pos.y+=n.y*62;p.invuln=.28;p.perfect=.13;this.start(p,{name:"闪身",windup:.36,active:0,recovery:0,damage:0,posture:0,range:0,level:0,dodge:true})}
 resolve(a,d,m){if(m.dodge)return;if(distance(a.pos,d.pos)>m.range)return;if(d.invuln>0){if(d.perfect>0){if(d===this.player&&d.style===1)d.edge=Math.min(3,d.edge+1);this.initiative=clamp(this.initiative+(d===this.player?18:-18),-100,100);this.log(d.style===1?"流影 · 完美闪避：锋意 +1。":"完美闪避。");this.spark(d.pos,"#79c8b8",14)}return}if(a.attack&&d.attack&&d.state==="active"&&!m.unblockable&&!d.attack.unblockable){const al=m.level||1,dl=d.attack.level||1;if(al===dl){a.posture=Math.max(0,a.posture-9);d.posture=Math.max(0,d.posture-9);this.log("对刀：双刃相抵。") }else{const win=al>dl?a:d,lose=win===a?d:a;lose.posture=Math.max(0,lose.posture-24);lose.stagger=.38;lose.state="stagger";lose.attack=null;if(win===this.player&&win.style===0)win.edge=Math.min(3,win.edge+1);this.initiative=clamp(this.initiative+(win===this.player?25:-25),-100,100);this.log(win===this.player?"压刀：锋意 +1。":"崩刀：你的刀被压开。") }this.hitStop=.055;this.shake=7;this.spark(a.pos,"#e7dfcf",18);return}if(d===this.player&&d.state==="guard"&&!m.unblockable){if(this.time-d.guardAt<=.19){a.posture=Math.max(0,a.posture-36);a.stagger=.46;a.state="stagger";a.attack=null;if(d.style===0)d.edge=Math.min(3,d.edge+1);this.initiative=clamp(this.initiative+30,-100,100);this.log("听刃 · 精准弹反：锋意 +1。");this.spark(d.pos,"#91bfb3",22);this.checkPosture(a)}else{d.posture=Math.max(0,d.posture-m.posture*.72);this.log("格挡成功，但架势承压。");this.checkPosture(d)}return}d.health=Math.max(0,d.health-m.damage);if(!m.execute)d.posture=Math.max(0,d.posture-m.posture*.34);d.flash=.14;this.initiative=clamp(this.initiative+(a===this.player?10:-13),-100,100);this.log(m.execute?"处决。":`${m.name}命中。`);this.hitStop=m.execute?.11:.035;this.shake=m.unblockable?10:5;this.spark(d.pos,m.unblockable?"#ad3826":"#ddd4c1",m.execute?28:13);this.checkPosture(d)}
 checkPosture(f){if(f.posture<=0&&f.alive()){f.stagger=1.75;f.state="stagger";f.attack=null;this.log(`${f.kind==="player"?"无铭者":"执刃者"}架势崩溃！`)}}
 chooseEnemyAttack(){const e=this.enemy,key=e.pattern[e.patternIndex%e.pattern.length];e.patternIndex++;this.start(e,enemyMoves[key]||enemyMoves.cut)}
 spark(p,color,count){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*220;this.particles.push({x:p.x,y:p.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,ttl:.18+Math.random()*.2,color})}}
 finish(){if(!this.player.alive())this.show("试刃失败","灰窑再铸","回想刚才是早挡、贪刀，还是把红招当成了普通刀。");else if(!this.enemy.alive())this.show("执刃者倒下","错籍之一","铭牌背面刻着：我有名，不是这个。换一种军式，再赢一次。")}
 show(title,eyebrow,body){if(this.resultShown)return;this.resultShown=true;ui.title.textContent=title;ui.eyebrow.textContent=eyebrow;ui.body.textContent=body;ui.result.classList.remove("hidden")}
 draw(){X.save();X.clearRect(0,0,1280,720);X.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);this.arena();this.fighter(this.enemy);this.fighter(this.player);for(const p of this.particles){X.globalAlpha=clamp(p.ttl*4,0,1);X.fillStyle=p.color;X.fillRect(p.x-2,p.y-2,4,4)}X.globalAlpha=1;this.hud();X.restore()}
 arena(){const g=X.createRadialGradient(640,380,80,640,380,560);g.addColorStop(0,"#2a2922");g.addColorStop(1,"#090b09");X.fillStyle=g;X.fillRect(0,0,1280,720);X.strokeStyle="rgba(182,150,99,.2)";X.lineWidth=2;X.beginPath();X.ellipse(640,397,480,245,0,0,Math.PI*2);X.stroke();for(let x=220;x<=1060;x+=70){X.beginPath();X.moveTo(x,210);X.lineTo(x-120,595);X.stroke()}for(let y=235;y<=585;y+=58){X.beginPath();X.moveTo(180,y);X.lineTo(1100,y);X.stroke()}X.fillStyle="#181712";X.fillRect(420,92,440,75);X.fillStyle="#a87742";X.font="20px serif";X.textAlign="center";X.fillText("造 像 署 · 校 刀 院",640,140)}
 fighter(f){X.save();X.translate(f.pos.x,f.pos.y);X.rotate(f.face);const player=f.kind==="player";X.fillStyle="rgba(0,0,0,.45)";X.beginPath();X.ellipse(0,17,35,16,0,0,Math.PI*2);X.fill();X.fillStyle=f.flash>0?"#fff1de":player?"#d8d0bd":"#332b25";X.strokeStyle=player?(f.style===0?"#91bfb3":"#718876"):"#a43b29";X.lineWidth=5;X.beginPath();X.ellipse(0,0,player?25:28,player?30:34,0,0,Math.PI*2);X.fill();X.stroke();const wind=f.attack&&f.state==="windup";X.strokeStyle=wind&&f.attack.unblockable?"#ef422d":wind?"#d2a55f":"#d7d1c4";X.lineWidth=wind&&f.attack.unblockable?9:6;X.beginPath();X.moveTo(10,-5);X.lineTo(72,f.state==="active"?25:-22);X.stroke();if(wind){X.strokeStyle=f.attack.unblockable?"#ef422d":"#d2a55f";X.beginPath();X.arc(0,0,42,-Math.PI/2,-Math.PI/2+Math.PI*2*clamp(f.timer/f.attack.windup,0,1));X.stroke()}X.restore()}
 bar(x,y,w,v,max,color,label){X.fillStyle="rgba(0,0,0,.7)";X.fillRect(x,y,w,12);X.fillStyle=color;X.fillRect(x+2,y+2,(w-4)*clamp(v/max,0,1),8);X.fillStyle="#d7d1c4";X.font="13px sans-serif";X.textAlign="left";X.fillText(label,x,y-5)}
 hud(){X.fillStyle="rgba(7,9,8,.76)";X.fillRect(430,20,420,94);X.fillStyle="#ded7c7";X.font="20px serif";X.textAlign="center";X.fillText("造像署执刃者",640,46);this.bar(470,60,340,this.enemy.health,this.enemy.maxHealth,"#8e3024","命");this.bar(470,91,340,this.enemy.posture,this.enemy.maxPosture,"#b1884d","势");X.fillStyle="rgba(7,9,8,.76)";X.fillRect(24,548,330,145);X.fillStyle="#ded7c7";X.textAlign="left";X.fillText(`长刀 · ${styles[this.player.style].name}`,43,579);this.bar(43,600,280,this.player.health,this.player.maxHealth,"#8e3024","生命");this.bar(43,633,280,this.player.posture,this.player.maxPosture,"#b1884d","架势");X.fillStyle=this.player.style===0?"#91bfb3":"#718876";X.font="18px serif";X.fillText(`锋意 ${"◆".repeat(this.player.edge)}${"◇".repeat(3-this.player.edge)}`,43,681);X.fillStyle="#4a3c2e";X.fillRect(490,130,300,8);X.fillStyle=this.initiative>=0?"#91bfb3":"#ad3826";X.fillRect(635+this.initiative*1.4,124,10,20);X.fillStyle="#998f7f";X.textAlign="center";X.font="12px sans-serif";X.fillText("势权",640,158);X.fillStyle="#d7d1c4";X.font="14px sans-serif";X.fillText(this.logs[0]?.text||"读他的刀。",640,680);if(this.telegraph&&this.enemy.attack){X.fillStyle=this.telegraph.unblockable?"#ef422d":"#d6b36f";X.font="23px serif";X.fillText(`${this.telegraph.name} · ${this.telegraph.hint}`,640,198)}if(this.enemy.posture<=0&&this.enemy.alive()){X.fillStyle="#f0b94f";X.font="26px serif";X.fillText("破势 · 靠近按斩处决",640,238)}}
}
const game=new Game();game.enemy.chooseAttack=()=>game.chooseEnemyAttack();
function action(name,down){if(down&&!input.held[name])input.just.add(name);input.held[name]=down}
const keys={KeyJ:"attack",KeyK:"guard",Space:"dodge",ShiftLeft:"dodge",KeyQ:"skill1",KeyU:"skill1",KeyE:"skill2",KeyI:"skill2",Tab:"switch",KeyR:"restart"};
window.addEventListener("keydown",e=>{input.keys.add(e.code);if(keys[e.code]){e.preventDefault();action(keys[e.code],true)}});window.addEventListener("keyup",e=>{input.keys.delete(e.code);if(keys[e.code]){e.preventDefault();action(keys[e.code],false)}});C.addEventListener("pointerdown",e=>action(e.button===2?"guard":"attack",true));C.addEventListener("pointerup",e=>action(e.button===2?"guard":"attack",false));C.addEventListener("contextmenu",e=>e.preventDefault());
document.querySelectorAll("[data-action]").forEach(b=>{const n=b.dataset.action;b.addEventListener("pointerdown",e=>{e.preventDefault();b.classList.add("active");action(n,true)});for(const t of ["pointerup","pointercancel"])b.addEventListener(t,e=>{e.preventDefault();b.classList.remove("active");action(n,false)})});
let pointer=null;function moveStick(e){const r=ui.stick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,n=unit(x,y),m=Math.min(r.width*.35,Math.hypot(x,y));input.move={x:n.x*m/(r.width*.35),y:n.y*m/(r.width*.35)};ui.knob.style.transform=`translate(${n.x*m}px,${n.y*m}px)`}ui.stick.addEventListener("pointerdown",e=>{pointer=e.pointerId;moveStick(e)});ui.stick.addEventListener("pointermove",e=>{if(e.pointerId===pointer)moveStick(e)});for(const t of ["pointerup","pointercancel"])ui.stick.addEventListener(t,e=>{if(e.pointerId===pointer){pointer=null;input.move={x:0,y:0};ui.knob.style.transform="translate(0,0)"}});
$("startButton").addEventListener("click",()=>{ui.intro.classList.add("hidden");game.running=true});$("restartButton").addEventListener("click",()=>game.reset(true));$("muteButton").addEventListener("click",e=>e.currentTarget.textContent=e.currentTarget.textContent==="声"?"静":"声");
let prev=performance.now();function frame(now){game.update(Math.min(.05,(now-prev)/1000||0));prev=now;game.draw();input.clearFrame();requestAnimationFrame(frame)}
$("bootStatus").textContent="ready";window.__bladeBreath={game,input};if(new URLSearchParams(location.search).get("autostart")==="1")game.reset(true);requestAnimationFrame(frame);
})();
