#!/usr/bin/env python3
"""Build or verify the dependency-free browser prototype as one HTML file."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "prototype-web"
OUT = ROOT / "dist" / "Wuming-Zhangcheng-M0.html"


def render() -> str:
    html = (WEB / "index.html").read_text(encoding="utf-8")
    css = (WEB / "styles.css").read_text(encoding="utf-8")
    js = (WEB / "game.js").read_text(encoding="utf-8").replace("</script", "<\\/script")

    stylesheet = '<link rel="stylesheet" href="styles.css">'
    script = '<script src="game.js"></script>'
    if stylesheet not in html:
        raise SystemExit("stylesheet marker not found")
    if script not in html:
        raise SystemExit("script marker not found")

    html = html.replace(stylesheet, f"<style>\n{css}\n</style>")
    html = html.replace(script, f"<script>\n{js}\n</script>")
    return "<!-- Generated by scripts/build_web_single.py; edit prototype-web sources instead. -->\n" + html


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the committed single-file build is stale")
    args = parser.parse_args()

    expected = render()
    if args.check:
        if not OUT.exists():
            raise SystemExit(f"missing generated build: {OUT}")
        if OUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("standalone browser build is stale; run scripts/build_web_single.py")
        print(f"Standalone browser build is current: {OUT}")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(expected, encoding="utf-8")
    print(OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
